# Linear Algebra
### Realization of central concepts with Numpy and Scipy

In [1]:
import numpy as np
from scipy.linalg import null_space


### Dot Product
$
\mathbf{x}^T \mathbf{y} = \sum\limits_{i=1}^n x_i y_i
$

Example:  
$
\mathbf{x}=
\begin{pmatrix}
1 \\ 2 \\ 3
\end{pmatrix}
, 
\mathbf{y}=
\begin{pmatrix}
4\\ 5 \\ 6
\end{pmatrix}
, 
\mathbf{x}^T \mathbf{y} = 32
$

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x @ y

32

### General Inner Product
$
\mathbf{x}^T \mathbf{B} \mathbf{y} = \sum\limits_{i=1}^n x_i y_i
$

Example:  
$
\mathbf{x}=
\begin{pmatrix}
1 \\ 2 \\ 3
\end{pmatrix}
, 
\mathbf{y}=
\begin{pmatrix}
4\\ 5 \\ 6
\end{pmatrix}
, 
\mathbf{x}^T \mathbf{y} = 32
$

### Angles and scalar product
$
\cos{\omega} = \frac{\langle\mathbf{x},\mathbf{y}\rangle}{\|\mathbf{x}\|\|\mathbf{y}\|}
$


In [3]:
### example
np.arccos((x @ y)/(np.linalg.norm(x) * np.linalg.norm(y)))

0.2257261285527342

### Change of basis
$
\mathbf{B} = \mathbf{T^{-1}}\mathbf{A}\mathbf{T}
$

### Orthogonal projection
$
\pi_{U}(\mathbf{x})=\lambda \mathbf{b} = \frac{\mathbf{b}^T \mathbf{x}}{\|\mathbf{b}\|^2}\mathbf{b}
$
##### Proof:
$
\langle \mathbf{x}-\lambda\mathbf{b}, \mathbf{b}\rangle=0
$

Because of the bilinearity of the inner product we yield:  
$
\langle \mathbf{x}, \mathbf{b}\rangle - \lambda\langle\mathbf{b},\mathbf{b}\rangle
\iff
\lambda = \frac{\langle\mathbf{x},\mathbf{b}\rangle}{\|\mathbf{b}\|^2}
$

### Projection matrix
$
\begin{align}
\mathbf{P}_{\pi}\mathbf{x} & =\lambda \mathbf{b} \\
&= \mathbf{b}\frac{\mathbf{b}^T\mathbf{x}}{\|\mathbf{b}\|^2} = \frac{\mathbf{b}\mathbf{b}^T}{\|\mathbf{b}\|^2}\mathbf{x}
\end{align}
$

so:  
$
\mathbf{P}_{\pi} = \frac{\mathbf{b}\mathbf{b}^T}{\|\mathbf{b}\|^2}
$


In [4]:
#example
b =np.array([1, 2, 2]).reshape(-1, 1)
P_pi = np.dot(b, b.T)/np.linalg.norm(b)**2
P_pi

array([[0.11111111, 0.22222222, 0.22222222],
       [0.22222222, 0.44444444, 0.44444444],
       [0.22222222, 0.44444444, 0.44444444]])

### Eigenvalues and Eigenvectors

$
\begin{align}
\mathbf{A}\mathbf{x}=\lambda\mathbf{x}&\iff \mathbf{A}\mathbf{x}-\lambda\mathbf{x}=0 \\
& \iff (\mathbf{A} - \lambda\mathbf{I})\mathbf{x}=0\iff \mathbf{x}\in \text{ker}(\mathbf{A} -\lambda\mathbf{I})
\end{align}
$

In [5]:
# example
A=np.array([[4, 2],[1,3]])
# calculate characteristic polynomial
cpoly = np.poly(A)
print("Characteristic polynomial: {}".format(cpoly))
lambdas = np.roots(cpoly)
print("lambda 1: {}, lambda 2: {}".format(lambdas[0], lambdas[1]))
# set up list with null spaces:
ns_list = []
ns_array = np.zeros(shape=(2,2))
for l in lambdas:
    mat = A-l*np.identity(2) 
    ns_l = null_space(mat)
    ns_list.append((ns_l / ns_l[0]).flatten().tolist())
np.array(ns_list).T

Characteristic polynomial: [ 1. -7. 10.]
lambda 1: 5.0, lambda 2: 2.0


array([[ 1. ,  1. ],
       [ 0.5, -1. ]])

In [6]:
# or with function eig
np.linalg.eig(A)

(array([5., 2.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

# Decompositions

## Cholesky Decomposition

A symmetric, positive definite matrix $\mathbf{A}$ can be factorized into a product $\mathbf{A}=\mathbf{L}\mathbf{L}^\top$, where $\mathbf{L}$ is a lower-triangular matrix with positive diagonal elements.

Applications:
- generate samples from a Gaussian distribution (covariance matrix is symmetric, positive definite)
- perform linear transformations of random variables
- efficiently compute determinants
